makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-cayman
asignatura: Aprendizaje y enseñanza de la Tecnología
lista_cursos:
  - 1º ESO
  - 2º ESO
  - 3º ESO
  - 4º ESO
include:
  - assets
  - README.md
